// Generated by Wrangler by running `wrangler types`

interface Env {
	AISONGGENERATOR_USER_ID: string;
	AISONGGENERATOR_API_KEY: string;
	AISONGGENERATOR_REFRESH_TOKEN: string;
	DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").DO>;
}
